const ecomExpressStatusMapping = {
  "soft data uploaded": "Ready To Ship",
  "pickup assigned": "In-transit",
  "out for pickup": "In-transit",
  "pickup failed": "Ready To Ship",
  "pickup scheduled": "Ready To Ship",
  "field pickup done": "In-transit",
  bagged: "In-transit",
  "bag added to connection": "In-transit",
  "departed from location": "In-transit",
  "redirected to another": "In-transit",
  "bag inscan at location": "In-transit",
  "origin facility inscan": "In-transit",
  "shipment inscan at location": "In-transit",
  "shipment debagged at location": "In-transit",
  "redirected to another delivery center (dc update) ": "In-transit",
  "out for delivery": "Out for Delivery",
  undelivered: "Undelivered",
  "mass update": "Undelivered",
  delivered: "Delivered",
  "arrived at destination": "In-transit",
  "ofd lock": "RTO",
  "rto lock": "RTO",
  returned: "RTO In-transit",
  cancelled: "Cancelled",
  lost: "Cancelled",
  // undelivered: "In-transit",
  "not picked": "Ready To Ship",
};

module.exports = ecomExpressStatusMapping;
