const VamashipStatusMapping = {
  "booking pending": "Ready To Ship",
  "shipment booked": "Ready To Ship",
  "shipment manifested": "Ready To Ship",
  "cancel requested": "Undelivered",
  "missed pickup": "Undelivered",
  "pickup cancelled": "Undelivered",
  "pickup scheduled": "Ready To Ship",
  "pickup re-scheduled": "Ready To Ship",
  "out for pickup": "Ready To Ship",
  "picked up from origin": "In-transit",
  "shipment in-transit": "In-transit",
  "shipment cancelled": "Undelivered",
  "received at origin hub": "In-transit",
  "shipment on-hold": "In-transit",
  "received at destination hub": "In-transit",
  "shipment misrouted": "In-transit",
  "shipment lost": "Undelivered",
  "shipment damaged": "Undelivered",
  "unexpected challenge": "Undelivered",
  "address incorrect": "Undelivered",
  "delay in delivery expected": "In-transit",
  "shipment out for delivery": "Out for Delivery",
  "delivery attempt failed": "Undelivered",
  "partial delivery": "Undelivered",
  "pending": "In-transit",
  "contact customer support": "Undelivered",
  "delivered": "Delivered",
  "return shipment - initiated": "RTO",
  "return shipment - in transit": "RTO",
  "return shipment - exception": "RTO",
  "return shipment - delivered": "RTO",
  "tracking closed": "Delivered"
};

module.exports = VamashipStatusMapping;
