const SmartShipStatusMapping = {
  "order created": "Ready To Ship",
  "order confirmed": "Ready To Ship",
  "shipping label generated": "Ready To Ship",
  "manifested": "Ready To Ship",
  "pick up scan on field":"In-transit",
  "direct canvas bag scanned":"In-transit",
  "comm flight veh train delayed cancelled":"In-transit",
  "shipment outscanned to network":"In-transit",
  "shipment inscan":"In-transit",
  "re-way":"In-transit",
  "mixed canvas bag scanned":"In-transit",
  "canvas bag consolidated scan":"In-transit",
  "shipment outscan":"Out for Delivery",
  "call logs":"Out for Delivery",
  "shipped": "In-transit",
  "delivered": "Delivered",
  "delivery attempted - out of delivery area": "Undelivered",
  "delivery attempted - address issue": "Undelivered",
  "delivery attempted - cod not ready": "Undelivered",
  "delivery attempted - customer not available": "Undelivered",
  "delivery attempted - customer refused": "RTO",
  "delivery attempted - future delivery requested": "Undelivered",
  "return to origin": "RTO In-transit",
  "rto delivered to shipper": "RTO Delivered",
  "delivery attempted - open delivery requested": "Undelivered",
  "delivery attempted - others": "Undelivered",
  "courier assigned": "Ready To Ship",
  "in transit": "In-transit",
  "rto in transit": "RTO In-transit",
  "out for delivery": "Out for Delivery",
  "handed over to courier": "In-transit",
  "delivery confirmed by customer": "Delivered",
  "in transit delay - oda": "In-transit",
  "rto to be refunded": "RTO In-transit",
  "forward shipment lost": "RTO In-transit",
  "rto delivered to fc": "RTO Delivered",
  "misrouted": "In-transit",
  "destination reached": "In-transit",
  "delivery not attempted": "In-transit",
  "rto in transit - damaged": "RTO In-transit",
  "refused by customer with otp": "RTO"
};

module.exports = SmartShipStatusMapping;
