import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="container mx-auto p-6">
      <h1 className="text-2xl font-bold mb-4">Terms & Conditions</h1>
      <p className="mb-4">
        This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>
      <p className="mb-4">
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name <a href="https://www.shipexindia.com" className="text-blue-600">https://www.shipexindia.com</a> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
      </p>
      <p className="mb-4">
        The Platform is owned by SHIPEX INDIA, a company incorporated under the Companies Act, 1956, with its registered office at 01, Basement, Biju Tower, Baba Nagar, Bhiwani 127021 (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
      </p>
      <p className="mb-4">
        Your use of the Platform and services and tools are governed by the following terms and conditions ('Terms of Use') as applicable to the Platform, including the applicable policies which are incorporated herein by reference. By mere use of the Platform, you shall be contracting with the Platform Owner, and these terms and conditions, including the policies, constitute your binding obligations with the Platform Owner.
      </p>
      <h2 className="text-xl font-semibold mt-4">Terms of Use</h2>
      <ul className="list-disc pl-6 mb-4">
        <li>You agree to provide true, accurate, and complete information during and after registration.</li>
        <li>We do not provide any warranty or guarantee on the accuracy, timeliness, performance, or suitability of the information on this Platform.</li>
        <li>Your use of our Services and the Platform is solely at your own risk.</li>
        <li>The contents of the Platform and Services are proprietary and licensed to us.</li>
        <li>You acknowledge that unauthorized use of the Platform may lead to action against you.</li>
        <li>You agree to pay the charges associated with availing of the Services.</li>
        <li>You agree not to use the Platform for any unlawful activities.</li>
        <li>The website and Services may contain third-party links; accessing these links will be governed by their respective terms.</li>
        <li>Upon initiating a transaction, you enter into a legally binding contract with the Platform Owner.</li>
        <li>You shall indemnify and hold harmless the Platform Owner against any claims arising out of your breach of these terms.</li>
        <li>Parties shall not be liable for failure to perform obligations due to a force majeure event.</li>
        <li>These Terms shall be governed by the laws of India and subject to the jurisdiction of the courts in Bhiwani and Haryana.</li>
      </ul>
      <p className="mb-4">
        All concerns or communications relating to these Terms must be directed to us using the contact information provided on this website.
      </p>
    </div>
  );
};

export default TermsAndConditions;
